### ISSUE TITLE
question Azure Key Vault

### ISSUE THREAD

**Issue by Mrwh0** [sejpalkalpesh/eth-signer#1]
Support for Ethereum Transaction and Message Signing using Azure Key Vault using boto3?

**Comment by sejpalk** [comment]
An Azure Key Vault support isn't available in the 0.1.X version.  

Also, `boto3` is only required for AWS KMS support. 

For Azure Key Vault `eth-singner` will use [azure-sdk-for-python](https://github.com/Azure/azure-sdk-for-python)

Right now, I'm working on a `Vault by HashiCorp` related update. So, `Azure Key Vault ` support might take some more time.
